spring:
  config:
    activate:
      on-profile: kafka

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  cloud:
    stream:
      default-binder: kafka
      function:
        definition: logConsumer;logProducer
      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: localhost:9092
      bindings:
        logProducer-out-0:
          destination: log-topic
          content-type: application/json
        logConsumer-in-0:
          destination: log-topic
          group: logging-svc
          content-type: application/json
