spring:
  application:
    name: logging-svc
  profiles:
    active: kafka

server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, env
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
